version: 0.0

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building the app"
      - npm run build
artifacts:
  files:
    - '**/*'
